alphagov/short-url-manager

spec/controllers/short_url_requests_controller_spec.rb, spec/support/sso_helper.rb
- Doing a global find and replace across the app, it seems like
`expect_authourised` [sic] isn't used anywhere, so I've removed it.
=> Fix typo originating in a test helper: authourised => authorised

app/controllers/short_url_requests_controller.rb, app/views/dashboard/dashboard.html.erb, app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/list_short_urls.html.erb, app/views/short_url_requests/show.html.erb, config/routes.rb
- Based on https://www.agileplannerapp.com/boards/105200/cards/5112, this adds a page at `/list_all_redirects` that shows all of the accepted short URLs that this app knows about from its database and links out to their respective `show` pages.
- Depending on where the user comes from, display either the confirm/reject/back buttons or nothing at all in the case of coming from `/list_all_redirects`. The list all page should not, IMO, be a place to deal with the requests - that should go through "manage requests".
- Add a link to the new list page from the dashboard, only visible to managers.
:fire:
=> Add a list page showing all approved short URL requests in this app's database

Gemfile, Gemfile.lock
- This is helpful for simplifying https://github.com/alphagov/short-url-manager/pull/21.
I'm doing this update in a separate branch due to the fact that
this app is several major versions behind the most recent.
=> Upgrade the gds-api-adapters gem version to 17.3.0

app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/new.html.erb, spec/features/publisher_requests_a_furl_spec.rb
- Some users were getting the From/To URLs the wrong way around, causing
their requests to be rejected. Following feedback from Nayeema and Elena,
change these labels to be more descriptive.
- Many requestors deal with departments who want these short URLs via
Zendesk, and many of them put a link to the Zendesk ticket in the request
box, so explicitly mention that this is possible.
=> Change the wording of the From and To boxes and the Reason box help text

app/views/layouts/application.html.erb
- A user (Elena) demonstrated having to go back through pages to reach Signon to
switch between applications. This makes it consistent with many (but not all)
other admin apps, with a link in the top right hand corner of the header,
therefore on every page.
=> Add a link to the user's profile in Signon to the header

app/controllers/short_url_requests_controller.rb, app/models/short_url_request.rb, app/views/short_url_requests/new.html.erb, spec/controllers/short_url_requests_controller_spec.rb, spec/features/publisher_requests_a_furl_spec.rb, spec/models/short_url_request_spec.rb
- According to Nayeema, requestors (A) were having problems with
specifying that the request originated from someone else (B), and
therefore specifying person B's email address. This meant that
person A would not get updates about what was essentially their
requested short URL, and the approvers had to do lots of detective
work to find out who actually submitted the request through the tool
(person A) to go and talk to in case of problems or rejection.
- Remove the text field in the new request form and its associated
validations. Make the tests pass again.
*Screenshots*:
Before:
and
After:
and
:fire:
=> Automatically set the email address to that of the current user

app/views/short_url_requests/show.html.erb
- Users will presumably always want to get back to the main page, so show it at
all times not just when a request is pending review.
=> Make the back button on the show page always visible

db/migrate/20150122161704_import_router_data_short_urls.rb
Importing these redirects involves creating items in the content-store.
These requests occasionally timeout, causing the whole migration to
abort.  This adds a retry mechanism to retry each one up to 3 times on a
timeout.
=> Improve robustness of data import migration.

db/migrate/20150319115838_fix_european_growth_fund_url.rb
This migration updates the app's internal datastore to match changes made manually in production via router-data.
Not to be deployed until after router-data#357
=> Reslug european-growth-funding friendly URL

db/migrate/20150319115838_fix_european_growth_fund_url.rb
This hasn't been deployed, so it should be safe to just correct this
migration, rather than making a brand new one.  Preview won't get the
update, but the database will be blown away by the nightly sync there
shortly, anyway.
=> Correct the target url for the new ESI fund shurl

app/controllers/short_url_requests_controller.rb, app/views/short_url_requests/list_short_urls.html.erb, spec/features/short_url_manager_views_accepted_requests_spec.rb
- Unfortunately the table filter JavaScript module doesn't support
filtering over multiple pages, which would defeat the object of
having it there. I've therefore made the decision to remove the
pagination on the "list accepted short URLs page" and add a
search-like box to make finding a previous short URL a lot easier.
(Roo agrees that this is a good idea. :sunny: Taken most of the code from Transition when we did a [similar thing](https://github.com/alphagov/transition/commit/f8874f086048dc104df0f744355f0d32fff947d9).)
Before:
After:
(Of course, the data differences are preview vs. my dev VM's latest replication.)
=> Remove pagination on the list page in favour of filtering the table

db/migrate/20150715153119_update_european_growth_fund_short_url.rb
The existing Finder (at `/european-structural-investment-funds`) is being replaced
by a detailed guide and the short URL needs to be updated accordingly.
/cc @jamiecobbett
=> Update the short URL for /european-growth-funding

db/migrate/20150717153042_update_pip_toolkit_short_url.rb
This migration corrects the destination url 
from:  https://www.gov.uk/government/publications/the-personal-independence-payment-toolkit-for-partners/the-personal-independence-payment-pip-toolkit-for-partners
to: https://www.gov.uk/government/publications/the-personal-independence-payment-toolkit-for-partners
=> The destination url for this is incorrect and 404ing

db/migrate/20151001134351_remove_part_leave_profit_tax_credits_from_database.rb
This redirect was put in place as a temporary measure while a new Smart Answer
was being developed for HMRC.
The new Smart Answer (part-year-profit-tax-credits)[1] was deployed on Tue 29
Sep. Before the deployment we had to change the owner of this path in
url-arbiter from short-url-manager to smartanswers[2].
@jamiecobbett mentioned[3] that we should also remove the redirect from the
short-url-manager database now that it's no longer required.
I've followed the pattern in previous migrations of finding the
`ShortUrlRequest` and `Redirect` records we're interested in.
[1]: https://github.com/alphagov/smart-answers/pull/1942
[2]: https://github.com/alphagov/url-arbiter/pull/25
[3]: https://github.com/alphagov/url-arbiter/pull/25
=> Add migration to remove redirect

Rakefile
Adds a protective clause to check if RSpec is defined, this alleviates problems with rake tasks when RSpec isn't available.
=> Check if RSpec is defined

app/controllers/short_url_requests_controller.rb, app/views/short_url_requests/_existing_redirect.html.erb, app/views/short_url_requests/show.html.erb, spec/features/short_url_manager_responds_to_furl_requests_spec.rb
Paired with @NeilvB 
[Trello card](https://trello.com/c/D0Ibyt84/36-show-reviewers-if-they-will-overwrite-an-existing-redirect)
Reviewers can inadvertently overwrite existing short URL's without realising it because there is no immediate feedback that a redirect with the same `from_path` already exists.
Display a warning to the reviewer if accepting the short url request will overwrite an existing, live redirect.
Rather than refactoring the data model to give the history of every short URL request, having talked to Keith this appears to resolve the immediate user need from the reviewers side.
We are running a couple of subsequent stories to warn requesters they are requesting a duplicate to further reduce risk.
=> Warn reviewers if an existing redirect is present

spec/spec_helper.rb
1. Database cleaner should be run before the entire suite, incase some
data is left over from previous runs.
2. Truncation strategy with `database_cleaner` doesn't require starting.
3. Set the strategy once before the suite, not before each test.
=> Fix sporadic failure caused by stale test data

app/models/short_url_request.rb, lib/commands/short_url_requests/create.rb, spec/lib/commands/short_url_requests/create_spec.rb, spec/models/short_url_request_spec.rb
We don't want to create extra work for reviewers -- prevent raising a
request if a current Redirect already exists with the same from_path and
to_path.
I spotted a bug here in that if validation failed but confirmation was
required the validation wouldn't be checked until the confirmation was
sent, at which point the user is redirected to the form, and the
confirmation is lost, so they have to confirm again. Fix that by
massaging the order (and cover it with a spec).
=> Fail validation if an identical redirect exists

app/models/concerns/short_url_validations.rb, app/models/redirect.rb, app/models/short_url_request.rb, app/views/short_url_requests/_form.html.erb, config/locales/en.yml, spec/models/redirect_spec.rb, spec/models/short_url_request_spec.rb, spec/support/shared_examples_for_short_url_validations.rb
This is a companion to alphagov/publishing-api#531
[Trello card](https://trello.com/c/4vQu6mO4)
Our content designers need to be able to configure short URLs for gov.uk campaigns. For example, it needs to be possible to set up a redirect from `https://www.gov.uk/campaign-slug` to `http://my-campaign-title.campaign.gov.uk`.
This PR adds that functionality to short-url-manager.
Other changes in this PR:
* Use i18n for field names, so that the field labels match the validation error messages
* Extract the shared validation logic in `ShortUrlRequest` and `Redirect` into a concern
* Extract the shared examples in the specs for `ShortUrlRequest` and `Redirect` into a spec helper
=> Enable campaign redirects

app/models/concerns/short_url_validations.rb, spec/models/redirect_spec.rb, spec/models/short_url_request_spec.rb, spec/support/shared_examples_for_short_url_validations.rb
Related to #62
See also alphagov/publishing-api#534
* Update the `to_path` validations in the `ShortUrlValidations` concern to require HTTPS for gov.uk campaign URLs. This change affects both the `ShortUrlRequest` model and the `Redirect` model.
* Fix bug in rspec shared examples for `ShortUrlValidations`.
=> Require gov.uk campaign URLs to be served over HTTPS

app/services/organisation_importer.rb, config/initializers/airbrake.rb, config/initializers/gds_sso.rb, config/mongoid.yml, config/redis.yml, config/schedule.rb
Part of https://trello.com/c/BrKRdn4f/495-rebuild-gov-uk-app-deployment-pipeline
This app will be deployed by govuk-app-deployment so config is mostly held in ENV vars now.
Depends on https://github.com/alphagov/govuk-puppet/pull/5103
=> Use env vars in configs

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_other_requests.scss, app/controllers/short_url_requests_controller.rb, app/models/short_url_request.rb, app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/new_rejection.html.erb, app/views/short_url_requests/show.html.erb, db/migrate/20161122132139_move_accepted_requests_without_redirects_to_superseded.rb, lib/commands/short_url_requests/accept.rb, spec/factories/short_url_request_factories.rb, spec/features/short_url_manager_views_accepted_requests_spec.rb, spec/features/short_url_manager_views_furl_requests_spec.rb, spec/lib/commands/short_url_requests/accept_spec.rb, spec/models/short_url_request_spec.rb
For: https://trello.com/c/BJ5KTi8V/19-display-associated-requests-on-short-url-page
We want to show other requests for the same short url on the request page to give the user some context on what they might be about to overwrite if they accept this request.  We also change the system to mark any existing requests as 'superseded' when we accept a new request that overwrites it.
There are some extra notes in the commits, so worth reviewing commit-by-commit.
=> Show similar requests to admins

app/presenters/publishing_api.rb, config/application.rb, spec/presenters/publishing_api_presenter_spec.rb, spec/support/publishing_api_helper.rb
Schemas no longer accept the "format" field, so this app was trying to send invalid data.
This probably wasn't picked up by the schema tests because this app is not yet running on Jenkins-2.
=> Send document_type/schema_name to publishing-api.

app/mailers/notifier.rb, app/views/notifier/short_url_requested.html.erb, app/views/notifier/short_url_requested.text.erb, config/initializers/instance_name.rb, spec/mailers/notifier_spec.rb
We want to let the user know which environment sent the email they receive, particularly in the case of the "short url requested" emails, so people know if they can ignore it because it's not a production one.
For: https://trello.com/c/SAcBmzf3/85-include-indication-of-which-environment-sent-the-email-in-short-url-manager
See: https://github.com/alphagov/govuk-puppet/pull/5338 which adds the env var we need.
=> Indicate environment in emails

app/helpers/url_helper.rb, app/views/notifier/short_url_requested.html.erb, app/views/notifier/short_url_requested.text.erb, spec/helpers/url_helper_spec.rb, spec/mailers/notifier_spec.rb
These urls are hosted on the short-url-manager domain, not the public www
domain.  We could solve this by setting default_url_options on the mailer
but as we generat two types of urls (public and admin) it's not obvious
which host should be the default.  It's probably better to set neither
and force us to be specific when generating all urls.
=> Use correct host for links to short url requests in notification emails

app/controllers/application_controller.rb, spec/controllers/short_url_requests_controller_spec.rb, spec/factories/user_factories.rb, spec/features/publisher_requests_a_furl_spec.rb, spec/features/short_url_manager_responds_to_furl_requests_spec.rb, spec/features/short_url_manager_views_accepted_requests_spec.rb, spec/features/short_url_manager_views_furl_requests_spec.rb
For: https://trello.com/c/6yS2fcZ4/111-fix-short-url-manager-so-it-properly-respects-signon-signin-permission
Make sure we require 'signin' permission for people logging in to short-url-manager.  Without this unchecking the "access" checkbox in the signon UI would make admins think that someone can't login when in fact they still can.  If they don't have other permissions this isn't a huge problem, but if they do this might mean someone we don't want to be using the system to request or manage short urls is still able to.
Almost every other signon app requires 'signin' permission, and the `mock_gds_sso` strategy used in tests and development mode forces 'signin' permission on the user when it fakes the login.
=> Require signin permission

app/models/concerns/short_url_validations.rb, app/views/dashboard/dashboard.html.erb, app/views/short_url_requests/_form.html.erb, app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/accept_failed.html.erb, app/views/short_url_requests/confirmation.html.erb, app/views/short_url_requests/edit.html.erb, app/views/short_url_requests/index.html.erb, app/views/short_url_requests/new.html.erb, app/views/short_url_requests/new_rejection.html.erb, app/views/short_url_requests/show.html.erb, config/breadcrumbs.rb, config/locales/en.yml, spec/features/publisher_requests_a_furl_spec.rb, spec/features/short_url_manager_views_accepted_requests_spec.rb, spec/support/shared_examples_for_short_url_validations.rb
* https://trello.com/c/ZG120ZYH/16-5-update-short-url-manager
* https://trello.com/c/jmxMgLWf/21-make-it-so-that-gds-content-designers-can-implement-redirects-reliably
* https://github.com/alphagov/publishing-api/pull/874
* https://github.com/alphagov/publishing-api/pull/873
* https://github.com/alphagov/govuk-content-schemas/pull/605
Changes to the Publishing API and schemas are required in order to support this change.
This is part of work towards allowing content designers to create redirects without developer intervention or use of the router-data redirect system.
Broadens the definition that allows for “external” redirects from GOV.UK to the .campaign.gov.uk sub-domain to now allow redirects to any .gov.uk sub-domain.
The user interface changes are minimal tweaks in order to hit MVP …
=> Govuk subdomains

app/controllers/short_url_requests_controller.rb, app/models/redirect.rb, app/models/short_url_request.rb, app/presenters/publishing_api.rb, app/views/short_url_requests/_form.html.erb, app/views/short_url_requests/_short_url_request_data.html.erb, lib/tasks/publishing_api_fields.rake, spec/factories/redirect_factories.rb, spec/features/publisher_requests_a_furl_spec.rb, spec/features/short_url_manager_responds_to_furl_requests_spec.rb, spec/features/short_url_manager_views_furl_requests_spec.rb, spec/models/redirect_spec.rb, spec/presenters/publishing_api_presenter_spec.rb, spec/support/publishing_api_helper.rb
This is part of Content Tools team's 2 week blitz.
* https://trello.com/c/XM9DuwVN
* https://trello.com/c/jmxMgLWf
Router data passes these fields to the publishing api. Short-URL-Manager will need to as well in order for us to support decommissioning of router-data.
Adds to the form for creating and updating redirects two new drop downs: `Route type` and `Segments mode`.
=> Add route type and segments mode

app/controllers/short_url_requests_controller.rb, app/models/concerns/short_url_validations.rb, app/models/redirect.rb, app/models/short_url_request.rb, app/presenters/publishing_api.rb, app/views/dashboard/dashboard.html.erb, app/views/short_url_requests/_form.html.erb, app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/accept_failed.html.erb, app/views/short_url_requests/confirmation.html.erb, app/views/short_url_requests/edit.html.erb, app/views/short_url_requests/index.html.erb, app/views/short_url_requests/new.html.erb, app/views/short_url_requests/new_rejection.html.erb, app/views/short_url_requests/show.html.erb, config/breadcrumbs.rb, config/locales/en.yml, lib/tasks/publishing_api_fields.rake, spec/factories/redirect_factories.rb, spec/features/publisher_requests_a_furl_spec.rb, spec/features/short_url_manager_responds_to_furl_requests_spec.rb, spec/features/short_url_manager_views_accepted_requests_spec.rb, spec/features/short_url_manager_views_furl_requests_spec.rb, spec/models/redirect_spec.rb, spec/presenters/publishing_api_presenter_spec.rb, spec/support/publishing_api_helper.rb, spec/support/shared_examples_for_short_url_validations.rb
This includes the changes that were done in the blitz (2017), both those that were reverted after being merged in to master, and some unmerged changes.
To avoid any issues relating to the interface, an additional change has been added that restricts using the new functionality to users with a `advanced_options` permission, both in terms of making requests, and approving requests.
=> Revert reversion of blitz changes

app/presenters/publishing_api.rb, spec/features/short_url_manager_responds_to_furl_requests_spec.rb, spec/models/redirect_spec.rb, spec/presenters/publishing_api_presenter_spec.rb, spec/support/publishing_api_helper.rb
Instead the `content_id` is passed as part of the endpoint path, and this value inside the hash won't be used.
=> Don't present content_id as part of the payload

lib/tasks/import_redirects.rake
In the import_redirects rake task. These match the defaults in
router-api.
=> Set default values for type and segments mode

lib/tasks/import_redirects.rake
Previously the redirects:import rake task just skipped existing
redirects. But this does not allow for fixing redirects that were
imported incorrectly, so add the ability to enable updating them.
=> Enable updating redirects in redirects:import

app/controllers/short_url_requests_controller.rb, app/models/redirect.rb, app/models/short_url_request.rb, app/views/short_url_requests/_form.html.erb, app/views/short_url_requests/_short_url_request_data.html.erb, app/views/short_url_requests/show.html.erb, lib/commands/short_url_requests/accept.rb, spec/lib/commands/short_url_requests/accept_spec.rb, spec/models/redirect_spec.rb
Sometimes it is useful to be able to create a new redirect for a path that is currently occupied by content from a different app. This could happen for example when some content is removed and needs to be redirected to new content from a different publisher.
This change adds an "override existing" field to the advanced options on the URL request form, and when that is selected it explicitly sends a path reservation override to the publishing-api before creating the redirect.
=> Allow advanced users to override existing path reservations

app/models/short_url_request.rb, spec/models/short_url_request_spec.rb
With Rails 5 the `belongs_to` association was changed from having the
optional property default from true to false. This means that we now
receive validation errors when we try to update many records in the
database.
This switches this back to the previous behaviour. As per:
https://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html
=> ShortUrlRequest association with requester is optional

README.md, app/mailers/notifier.rb, app/models/user.rb, spec/factories/user_factories.rb, spec/features/publisher_requests_a_furl_spec.rb, spec/lib/commands/short_url_requests/create_spec.rb, spec/mailers/notifier_spec.rb
As this app is becoming the official way to create redirects, replacing
router-data, developers and 2nd line need permissions to do this
directly. At present, though, granting the "manage_short_urls"
permission also adds the user to the list of recipients of email requests
for new URLs from departments, which is unnecessary.
This change therefore uses a new permission, "receive_notifications", to
determine the list of users who will be notified by email when a URL is
requested. Ability to actually approve the request remains with the
"manage_short_urls" permission as before; so those with the former
permission will usually need the latter, but the reverse is not true.
Before deployment a separate change will be necessary in signon to add
the new permission and assign it to the current …
=> Split "receive notifications" to a new permission.

app/views/short_url_requests/confirmation.html.erb, config/initializers/gds_sso.rb, lib/commands/short_url_requests/accept.rb, spec/lib/commands/short_url_requests/accept_spec.rb, spec/lib/commands/short_url_requests/create_spec.rb
When using the segments mode advanced option, we were never able to set it to anything other than the default value of "ignore" because we weren't setting it correctly when we accepted a pending Short Url Request.
We were also not passing on these values when we showed the confirmation screen.
=> Fix segments mode preserve

Gemfile, Gemfile.lock, db/migrate/20171113151034_create_redirects_for_design_principles.rb
For: https://trello.com/c/M45WyUGZ/261-retire-design-principles
We use short-url-manager to create redirects for all the paths currently served, and ever handled by the design-principles app.  Most of these are handled by redirects published by the design-principles app, or that somehow exist in the router database via ad-hoc changes.  Pushing them through short-url-manager means we have a record of the change, and in an app that won't shortly be moved to the attic.
=> Retire design principles

db/migrate/20171113151034_create_redirects_for_design_principles.rb
For: https://trello.com/c/M45WyUGZ/261-retire-design-principles
This is a follow up to #104 after we tried it on integration and spotted that
the `/design-principles/style-guide.atom` resulted in a 500 error from
government-frontend (see: https://sentry.io/govuk/app-government-frontend/issues/386977691/events/9310503605/)
The process for a gone item is to send an unpublishing to the
publishing-api.  This makes changes to the internal db of publishing-api
and then presents the unpublished content to the content-store.  This in
turn changes the internal db of the content-store and presents the changes
to the router.
For a gone item we tell router to set the handler to "gone", but not if it
has any details (like an explanation or alternate url).  If that is the
case we tell the router to set …
=> Remove details from /design-principles/style-guide.atom gone item

app/models/redirect.rb
`params` isn’t valid, but `extra` is. This was preventing us logging
errors to Sentry and seeing the real errors in the application.
=> Use correct arguments for Sentry

config/brakeman.ignore
This is a known bug in Brakeman where it will warn about this issue when rendering a collection of models.
https://stackoverflow.com/questions/48172135/brakeman-warning-dynamic-render-path?rq=1
https://github.com/presidentbeef/brakeman/pull/529
=> Ignore a warning about dynamic render paths

config/redis.yml
This is changed so that this application can use redis in the
govuk-docker context.
=> Allow redis to be configured by environment variables

app/models/short_url_request.rb, config/environments/development.rb, config/initializers/gds_sso.rb, spec/models/short_url_request_spec.rb
This resolves an issue where users could not edit a request once the
request was accepted as the validator thought a redirect already
existed.
This has been done to resolve this 2nd link zendesk ticket: https://govuk.zendesk.com/agent/tickets/3806774
It also includes a couple of fixes for things I found while running the app for the first time.
=> Allow editing a request without a redirect change

app/models/redirect.rb, lib/tasks/redirect.rake, spec/models/redirect_spec.rb
This will make it easier to handle support requests to remove a redirect.
An example ticket: https://govuk.zendesk.com/agent/tickets/3813666
=> Add ability to unpublish a redirect

README.md
We are now accepting requests for top level redirects (e.g. `/foo` => `/government/etc/foo`),
so presumably the technical constraints have now been worked through.
=> Remove outdated note about top-level redirects

.rubocop.yml, Gemfile, Gemfile.lock, app/assets/stylesheets/layouts/_application.scss, app/assets/stylesheets/modules/_clickable_row.scss, app/assets/stylesheets/views/shared/_form_errors.scss, app/controllers/short_url_requests_controller.rb, app/mailers/application_mailer.rb, app/mailers/notifier.rb, app/models/redirect.rb, app/models/short_url_request.rb, config/initializers/instance_name.rb, lib/commands/short_url_requests/accept.rb, lib/commands/short_url_requests/reject.rb, lib/commands/short_url_requests/update.rb, lib/tasks/lint.rake
- I'm doing this as part of the GOV.UK Developer Tooling group: https://trello.com/c/pR7GEFfU/128-make-all-current-govuk-repos-use-rubocop-govuk-instead-of-govuk-lint.
- The commit messages have more info.
=> Use `rubocop-govuk` instead of `govuk-lint`

Gemfile, Gemfile.lock, app/mailers/notifier.rb, app/services/request_notifier.rb, config/environments/production.rb, lib/commands/short_url_requests/accept.rb, lib/commands/short_url_requests/create.rb, lib/commands/short_url_requests/reject.rb, spec/controllers/short_url_requests_controller_spec.rb, spec/lib/commands/short_url_requests/reject_spec.rb, spec/services/request_notifier_spec.rb
`mail-notify` allows a mailer class to simply inherit from their base mailer in order to use notify instead of normal email; this means we can keep all the same logic.
Based on https://github.com/alphagov/short-url-manager/pull/451 for the iteration over multiple recipients.
https://trello.com/c/6FJKUWIs/1794-3-short-url-manager-use-notify-instead-of-amazon-ses
=> Use the mail-notify gem to deliver via Notify instead of SES

Gemfile, Gemfile.lock
RE GOVUK are in the process of migrating Short URL Manager from Carrenza
to AWS. As part of this process we are going to switch from using a
self hosted Mongo instance to AWS DocumentDB. DocumentDB is running
the equivalent of MongoDB 3.6.0 (a higher version than we currently have on our server).
This means that the following gems need to be updated accordingly:
mongoid to 6.3.0
mongo to  2.5.0
Mongo has now been upgraded to 2.6.12 (from 2.4.9) so this update should not cause
any errors. Please see the Ruby/Mongo driver compatibility chart for more
information:
https://docs.mongodb.com/ruby-driver/master/reference/driver-compatibility/
=> Upgrade Gems Mongo & Mongoid

Gemfile.lock, app/helpers/application_helper.rb
These are the changes necessary to upgrade to Ruby 2.7.1
As there is a script to update all app Ruby versions at once, leaving the version as 2.6.6
One deprecation warning remaining, coming from the Mongoid gem, specifically this line https://github.com/mongodb/mongoid/blob/d49ed95569d68505fa6fe2041c7270540cb83fc3/lib/mongoid/errors/mongoid_error.rb#L51
=> Upgrade to ruby 2.7.1

config/routes.rb, spec/requests/healthcheck_spec.rb
Add healthchecks to check mongodb and SidekiqRedis to fulfil criteria
for continuous deployment.
Co-authored-by: Edward Kerry <edward.kerry@digital.cabinet-office.gov.uk>
=> Improve healthchecks in preparation for CD

.github/pull_request_template.md
Add a template to warn the user before merging that this app is
continuously deployed.
Co-authored-by: Edward Kerry 
<edward.kerry@digital.cabinet-office.gov.uk>
=> Add pull request template warning of CD

app/services/organisation_importer.rb
We currently get a warning from Brakeman for possible SQL injection from the organisations importer's redis-lock that is blocking other PRs from being merged.
This was added in https://github.com/alphagov/short-url-manager/pull/8 but appears to now be unnecessary as the Rails environment is always `production` in non-test and non-CI environments anyway and each environment has it's own Redis instance.
=> Fix Brakeman SQL Injection warning

app/services/request_notifier.rb, spec/services/request_notifier_spec.rb
https://trello.com/c/6a9IvIGQ/2384-fix-notificationsclientbadrequesterror-in-short-url-manager
=> Rescue exception

app/models/concerns/short_url_validations.rb, app/views/short_url_requests/_form.html.erb, spec/support/shared_examples_for_short_url_validations.rb
This is in order to bring our allowed redirect domains in line with what
is permitted (in the publishing api)[https://github.com/alphagov/publishing-api/blob/1e96c7ef416b641706c14290d539bb1d36a93fff/app/validators/routes_and_redirects_validator.rb#L168-L170]
Trello - https://trello.com/c/OE0mGWzN/1630-create-pharmacy-collect-short-urls-for-13-september
This can't be merged before [the matching pr in govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/pull/1072) has been deployed because this would lead to some confusing error messages and data inconsistency. 
=> Change the allowed domains for redirects

Gemfile, Gemfile.lock, app/controllers/short_url_requests_controller.rb, app/lib/commands/short_url_requests/destroy.rb, app/models/short_url_request.rb, app/views/short_url_requests/remove.html.erb, app/views/short_url_requests/show.html.erb, config/breadcrumbs.rb, config/routes.rb, lib/tasks/redirect.rake, spec/controllers/short_url_requests_controller_spec.rb, spec/lib/commands/short_url_requests/destroy_spec.rb
The app now supports deleting short-urls by users with the short-url-manager permission.
This replaces the prior process which required developers to take manual action on behalf of users to delete short url.
Co Authored By: @danacotoran 
=> Add short url deletion feature

app/models/redirect.rb, spec/models/redirect_spec.rb
Trello: https://trello.com/c/7zcunjyo
Follows on from: #653
Unreserve the base path in Publishing API when a redirect is deleted.
When a redirect is created using Short URL Manager, the ownership of that base path changes from the original publishing application to "short-url-manager" in Publishing API.
Currently, when the redirect is deleted, the unpublish type is set to "gone" rather than "redirect", but the base path is still owned by Short URL Manager, meaning that the original page cannot be republished, nor can the base path be used for a new page unless a developer brings up a rails console and manually calls the "unreserve_path" method.
Calling "unreserve_path" when the redirect is deleted removes this need for manual intervention.
⚠️ This repo is Continuously Deployed: make sure …
=> Unreserve path when redirect deleted

config/application.rb
This removes code changes that was applied for the transition to Rails
7. Now we have deployed on Rails 7 these are no longer needed.
=> Resolve post Rails 7 TODOs

app/services/organisation_importer.rb
Redis.current will be deprecated in Redis 5.0.
As Redis.current ultimately calls Redis.new we can migrate this method now to pave the way for future upgrades.
From Redis changelog from [5.0][1]:
‘Removed Redis.current. You shouldn't assume there is a single global Redis connection, use a connection pool instead, and libaries using Redis should accept a Redis instance (or connection pool) as a config. E.g. MyLibrary.redis = Redis.new(…).’
[Redis.current][2] just calls Redis.new so should just be able to swap methods.
[trello](https://trello.com/c/oGFWhrCO/1551-migrate-away-from-deprecated-redis-method)
=> Use Redis.new rather than Redis.current

app/helpers/url_helper.rb, app/services/organisation_importer.rb
This just gets rid of the deprecation warnings in the logs. No functional change.
=> Switch from deprecated `Plek.current` to `Plek.new`.

Gemfile.lock, app/helpers/url_helper.rb, app/services/organisation_importer.rb, app/views/layouts/application.html.erb, spec/services/request_notifier_spec.rb
Short URL Manager is one of the few repos that needs amends for https://github.com/alphagov/plek/pull/93#issuecomment-1319922899. So I've done the update manually and updated related gems.
More info in the commits
=> Bump Plek to version 5

.dockerignore, Dockerfile, Gemfile, Gemfile.lock, config/application.rb, config/boot.rb
- Add Dockerfile.
- Allow for Rails assets deployment to S3 by including the app name in the Rails assets path.
- Enable [bootsnap](https://github.com/Shopify/bootsnap#bootsnap-) to reduce resource usage spikes on startup.
Tested: builds and comes up healthy on the integration Kubernetes cluster.
=> Add Dockerfile to define the container image build.

config/initializers/sidekiq.rb
We're going through out apps that use Sidekiq and enforcing Sidekiq strict args to ensure we're compatible with Sidekiq 7.
https://trello.com/c/JXAvbpOX/1103-upgrade-apps-to-sidekiq-v6
=> Enforce Sidekiq strict args

app/models/concerns/short_url_validations.rb, app/views/short_url_requests/_form.html.erb, spec/support/shared_examples_for_short_url_validations.rb
- update hosts list to match equivalent list in publishing API
- add moneyhelper.org.uk as per https://govuk.zendesk.com/agent/tickets/5516679
=> Update allowed hosts / allow moneyhelper org.uk

Gemfile, Gemfile.lock, app/views/layouts/_google_tag_manager.html.erb, app/views/layouts/application.html.erb, config/environments/test.rb
Google Tag Manager (GTM) can be included on all pages of the app by configuring the following environment variables:
- GOOGLE_TAG_MANAGER_ID
- GOOGLE_TAG_MANAGER_AUTH
- GOOGLE_TAG_MANAGER_PREVIEW
All three variables are optional.
If none are set, GTM will not be included on the page.
If only GOOGLE_TAG_MANAGER_ID is set, the default environment of the GTM container will be used.
If GOOGLE_TAG_MANAGER_AUTH and GOOGLE_TAG_MANAGER_PREVIEW are set, the specified GTM container environment will be used. This is used for managing the rollout of changes to integration so they can be tested before rolling out to production.
Trello card: https://trello.com/c/Wcuq3R1S/2167-add-ga4-page-view-tracking-to-apps-that-we-own
=> Add Google Tag Manager snippet

config/environments/production.rb, config/environments/test.rb
We were getting the error:
```SassC::SyntaxError: Internal Error: Incompatible units: 'px' and 'rem'.```
when images are being built on the Deploy CI action.
Attempting to fix via adding different asset compression also to production.rb
=> Sass error while building image upon deployment

.gitignore, Gemfile, Gemfile.lock, app/assets/config/manifest.js, app/lib/tasks/assets.rake, config/application.rb, config/environments/development.rb, config/initializers/dartsass.rb
LibSass has been deprecated. We're moving to Dart Sass. This follows the upgrade guide found here
https://docs.publishing.service.gov.uk/manual/migrate-to-dart-sass-from-libsass.html
https://trello.com/c/qeNHFPZN/1667-migrate-to-dart-sass
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if …
=> Migrate to dart sass

config/environments/production.rb
This configuration was lost during the upgrade to Rails 7.1. See 90eb0b9e9ff1da1e445aaeba242ea5efe5e7ae20
=> Configure action mailer to use GOV.UK Notify

app/helpers/url_helper.rb, spec/helpers/url_helper_spec.rb
govuk_url_for is used in three places in this codebase, all in view code like:
<%= link_to short_url_request.to_path, govuk_url_for(short_url_request.to_path) %>
`to_path` can be an absolute URL though, and in this case the application will render a link like:
<a href="http://gov.ukhttp://example.com">http://example.com</a>
which is real clown shoes stuff.
Addressable's URI.join method basically does what we want - if we're given a path, it will join that on to the website root, if we're given an absolute URL it will give us that.
=> Fix links to absolute URLs

Gemfile, Gemfile.lock
These changes wrap up the upgrade to FE5.
- Replace uglifier with terser.
- There was no need to separate out ES6 modules components since this app does not use any. In the future, such components would need to be imported separately. Follow instructions in the [documentation](https://docs.google.com/document/d/1uwip7pzQwM7t5ghn9_8KrsWXLePSRUltFPZ5fYw6Ab8/edit#heading=h.r2y7qlyvg991). See also [example PR](https://github.com/alphagov/manuals-publisher/pull/2484/files).
[Trello card](https://trello.com/c/vbqszQXq/2762-update-publishing-apps-to-govukpublishingcomponents-v4000)
=> Finish upgrade to frontend 5

.github/dependabot.yml, .github/workflows/copy-pr-template-to-dependabot-prs.yml, .github/workflows/rspec.yml
- Update instances of checkout@v3 to checkout@v4 in Github actions
- Update instance of github-script@v6 to github-script@v7
- Add dependabot configuration to raise PRs for updates to Github actions 
The linting of github actions is failing due to actions using checkout@v3 and github-script@v6. Upgrading to checkout@v4 github-script@v7 fixes the problem.
Adding a check in dependabot for updates to Github actions will automate this process in future
=> Update Github Actions to latest versions
