app/views/short_url_requests/list_short_urls.html.erb
spec/features/short_url_manager_views_accepted_requests_spec.rb

Also add a feature spec for it.

Add pagination buttons to accepted request view.

---

Gemfile
Gemfile.lock

- Tested in dev and nothing seems to be broken...

Bump govuk_admin_template to 2.2.0

---

app/models/short_url_request.rb
app/views/short_url_requests/_form.html.erb
spec/factories/short_url_request_factories.rb
spec/features/short_url_manager_responds_to_furl_requests_spec.rb

A consistency tweak and a bug fix following https://github.com/alphagov/short-url-manager/pull/41

Follow up fixes

---

app/models/redirect.rb

https://trello.com/c/tx50hSOx/492-add-bearer-token-value-to-all-apps-using-publishing-api

Use bearer token for publishing API authentication

---

app/views/notifier/short_url_request_accepted.html.erb
app/views/notifier/short_url_request_accepted.text.erb

- Spotted this in https://govuk.zendesk.com/agent/tickets/1258867 and thought I'd just fix it. :sunny:

Fix typo in 'short url accepted' email: redirectes => redirects

---

LICENCE
README.md

Update the README to follow the GOV.UK styleguide and add the MIT License.

Fix README as per styleguide

---

app/services/organisation_importer.rb
config/redis.yml

Some small config updates for redis and mongoid.

Use rails application config for

---

lib/tasks/import_redirects.rake

This is a one off task for importing data from router-data.

Add a rake task to import redirects

---

router-data-import/not-in-publishing-api.csv

Redirects to `http://` urls or non `gov.uk` urls will be rejected by short-url
manager.

We only want to try and create redirects where we know they will succeed

---

lib/tasks/import_redirects.rake

Some redirects in router-data have no content in the Publishing API,
but a path reservation exists. This needs explicitly changing before
Short URL Manager can successfully publish a redirect.

Support overriding path reservations in the redirect importer

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layouts/_application.scss
app/assets/stylesheets/modules/_button_to.scss
app/assets/stylesheets/modules/_clickable_row.scss
app/assets/stylesheets/modules/_form.scss
app/assets/stylesheets/views/shared/_form_errors.scss
app/views/shared/_form_errors.html.erb
app/views/short_url_requests/_short_url_request.html.erb
app/views/short_url_requests/list_short_urls.html.erb
spec/helpers/form_helper_spec.rb

Since new linting criteria were added to govuk-lint-sass, we need
to update our code so it passes.

Fix Sass linting errors

---

README.md

Fixes markdown formatting so heading can be rendered correctly.

Fix technical documentation README heading

---

app/models/short_url_request.rb
app/views/short_url_requests/_form.html.erb
lib/commands/short_url_requests/update.rb
spec/factories/user_factories.rb
spec/features/edit_live_url_redirect_or_short_url_feature.rb

These changes allow you to edit the advanced features of a live redirect or short URL.

Allow edit of advanced features

---

app/helpers/url_helper.rb
app/views/layouts/application.html.erb
config/initializers/gds_sso.rb
spec/mailers/notifier_spec.rb

Where an external URL is required.

Use the new external_url_for method in Plek

---

app/controllers/application_controller.rb

Signon now performs this check.

Replace require_signin_permission!

---

config/initializers/logstasher.rb

This is handled by govuk_app_config.
[Trello Card](https://trello.com/c/SGjLro0k/498-understand-our-current-logging-levels-and-maybe-reduce-them-in-production)

Remove custom logstasher config

---

.rubocop.yml
Rakefile
db/migrate/20150122161704_import_router_data_short_urls.rb
db/migrate/20150319115838_fix_european_growth_fund_url.rb
db/migrate/20150715153119_update_european_growth_fund_short_url.rb
db/migrate/20150717153042_update_pip_toolkit_short_url.rb
db/migrate/20151001134351_remove_part_leave_profit_tax_credits_from_database.rb
db/migrate/20151112141831_remove_duplicate_redirects.rb
db/migrate/20161122132139_move_accepted_requests_without_redirects_to_superseded.rb
db/migrate/20171113151034_create_redirects_for_design_principles.rb

This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.

Make entire repository pass Rubocop linting

---

Jenkinsfile

This is a first step to migrating this repo away from a master branch.

Update Jenkinsfile to use main branch

---

Jenkinsfile

The master/main detection has been merged.

Use default branch of govuk-jenkinslib

---

README.md
startup.sh

[Trello card](https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh)

Remove startup.sh and add govuk-docker to README

---

README.md

Add a minor grammatical fix to the documentation

---

Gemfile
Gemfile.lock

Revert bump mail pr

---

config/environments/production.rb

Fix ssl config
